name: chissoku
services:
  devcontainer:
    hostname: chissoku
    build:
      context: .
    environment:
      - LANG=ja_JP.UTF-8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../:/work/chissoku
      - home:/home/vscode
    command: sleep infinity

volumes:
  home:
